"""Adjust score and member relationship

Revision ID: 0c4a9f6feea4
Revises: d35e41e918de
Create Date: 2022-03-28 13:55:45.739037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4a9f6feea4'
down_revision = 'd35e41e918de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'date_processed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('date_processed', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
