"""Add bot column

Revision ID: 2bfd0df10a94
Revises: 426c1761f0bb
Create Date: 2022-03-21 20:11:23.185154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfd0df10a94'
down_revision = '426c1761f0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('bot', sa.Boolean(), nullable=True))
    op.execute('UPDATE member SET bot = false')
    op.alter_column('member', 'bot', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'bot')
    # ### end Alembic commands ###
