"""Rename user table to member

Revision ID: 426c1761f0bb
Revises: d30caaad93d0
Create Date: 2022-03-21 19:28:42.404036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426c1761f0bb'
down_revision = 'd30caaad93d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_author_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_replying_to_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'member', ['author'], ['id'])
    op.create_foreign_key(None, 'message', 'member', ['replying_to'], ['id'])
    op.add_column('reaction', sa.Column('member_id', sa.String(), nullable=False))
    op.drop_constraint('reaction_user_id_fkey', 'reaction', type_='foreignkey')
    op.create_foreign_key(None, 'reaction', 'member', ['member_id'], ['id'])
    op.drop_column('reaction', 'user_id')
    op.add_column('score', sa.Column('member_id', sa.String(), nullable=False))
    op.drop_constraint('score_user_id_fkey', 'score', type_='foreignkey')
    op.create_foreign_key(None, 'score', 'member', ['member_id'], ['id'])
    op.drop_column('score', 'user_id')
    op.add_column('voice_event', sa.Column('member_id', sa.String(), nullable=False))
    op.drop_constraint('voice_event_user_id_fkey', 'voice_event', type_='foreignkey')
    op.create_foreign_key(None, 'voice_event', 'member', ['member_id'], ['id'])
    op.drop_column('voice_event', 'user_id')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_event', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voice_event', type_='foreignkey')
    op.create_foreign_key('voice_event_user_id_fkey', 'voice_event', 'user', ['user_id'], ['id'])
    op.drop_column('voice_event', 'member_id')
    op.add_column('score', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.create_foreign_key('score_user_id_fkey', 'score', 'user', ['user_id'], ['id'])
    op.drop_column('score', 'member_id')
    op.add_column('reaction', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reaction', type_='foreignkey')
    op.create_foreign_key('reaction_user_id_fkey', 'reaction', 'user', ['user_id'], ['id'])
    op.drop_column('reaction', 'member_id')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_replying_to_fkey', 'message', 'user', ['replying_to'], ['id'])
    op.create_foreign_key('message_author_fkey', 'message', 'user', ['author'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numbers', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
