"""Change datetime to date

Revision ID: 8d573ab5dd45
Revises: a60ce787e38e
Create Date: 2022-03-30 23:17:41.331628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d573ab5dd45'
down_revision = 'a60ce787e38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
