"""Add sticker column

Revision ID: a60ce787e38e
Revises: 0c4a9f6feea4
Create Date: 2022-03-28 22:21:13.845534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60ce787e38e'
down_revision = '0c4a9f6feea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('sticker', sa.Boolean(), nullable=True))
    op.execute('update attachment set sticker = False')
    op.alter_column('attachment', 'sticker', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'sticker')
    # ### end Alembic commands ###
