"""Add type to channel

Revision ID: d35e41e918de
Revises: c1e491631a36
Create Date: 2022-03-26 16:01:03.262077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35e41e918de'
down_revision = 'c1e491631a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('type', sa.String()))
    op.execute('update channel set type = \'text\'')
    op.alter_column('channel', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'type')
    # ### end Alembic commands ###
